### PR TITLE
TrasnferAsset2

### LINKED ISSUE #623: Prevent asset transfer to inactivated account
### Background
There are reports that instead of swapping NCG to WNCG, users sent the NCG to their Ethereum address in the Nine Chronicles network

### Problem
The recipient cannot generate any valid transaction without activation code. So the received NCG is locked.

### Preventive measure
Asset transfer such as NCG transfer should check the recipient is activate or not. If the recipient is inactivated, the transaction should be failed

### Solution for the Problem
It should be debated first within dev/ops in Planetarium team

### PR DESCRIPTION
**Pull request by riemannulus**
This PR resolve #623

### CODE REVIEW

**Comment by kfangw** [comment]
btw, it is not easy for me to check the diff between old one and the patch. 
Could you explain with the pin point?

**Comment by riemannulus** [comment]
> 
> 
> btw, it is not easy for me to check the diff between old one and the patch.
> Could you explain with the pin point?

https://github.com/planetarium/lib9c/pull/636/files#diff-af422b0b2b534088a52121cf2e8094a42c2ef5e73db0a97fc1dd924e46ecc052R87-R96

Get all activated account list from chain, check is list contained recipient address. if not, throw error. if yes, send NCG.

File: Lib9c/Action/TransferAsset.cs [hunk 1]
```diff
@@ -84,6 +84,17 @@ public override IAccountStateDelta Execute(IActionContext context)
                 throw new InvalidTransferRecipientException(Sender, Recipient);
             }
 
+            if (state.GetState(Addresses.ActivatedAccount) is Dictionary asDict)
```
Comment (kfangw) [inline Lib9c/Action/TransferAsset.cs:87]: 👍

File: Lib9c/Action/TransferAsset.cs [hunk 2]
```diff
@@ -84,6 +84,17 @@ public override IAccountStateDelta Execute(IActionContext context)
...
+            {
+                var activatedAccountsState = new ActivatedAccountsState(asDict);
+                var activatedAccounts = activatedAccountsState.Accounts;
+                if (activatedAccounts.Count != 0
+                    && !activatedAccounts.Contains(Recipient))
+                {
+                    throw new InvalidTransferRecipientException(Sender, Recipient);
```
Comment (kfangw) [inline Lib9c/Action/TransferAsset.cs:94]: I am not sure. But it would be better to define the exception for this case.

**Comment by kfangw** [comment]
I don't see any relevant test case for this action. Do we need the test case,  which being executed in the CI, for newly introduced action type?

File: Lib9c/Action/TransferAsset.cs (hunk 2 above)
Comment (riemannulus) [reply Lib9c/Action/TransferAsset.cs:94]: It was vague to me. `InvalidTransferRecipientExecption` is perfect fit here too. but this error also mean sender and recipient are same. so, what is your opinion? If create new exception type, what name would be better?

Comment (kfangw) [reply Lib9c/Action/TransferAsset.cs:94]: Someone who catch the exception does not know the reason why the exception thrown; due to the recipient is inactivated. 

`I am not sure` means I have no idea how the exception handled by the someone. If the exception is suitable for this case in your thought, it is good to me too.

Comment (riemannulus) [reply Lib9c/Action/TransferAsset.cs]: I clearly make new exception for this case. c72621a

File: .Lib9c.Tests/Action/TransferAssetTest.cs [hunk 3]
```diff
@@ -227,6 +231,38 @@ public void ExecuteWithMinterAsRecipient()
             Assert.Equal(_recipient, ex.Recipient);
         }
 
+        [Fact]
+        public void ExecuteWithUnactivatedRecipient()
```
Comment (kfangw) [inline .Lib9c.Tests/Action/TransferAssetTest.cs:235]: ❤️

File: Lib9c/Action/TransferAsset.cs (hunk 1 above)
Comment (longfin) [reply Lib9c/Action/TransferAsset.cs:87]: AFIK, we split monolithic `ActivatedAccountsState` to many derived states [here](https://github.com/planetarium/lib9c/pull/509). so I think we should check derived address (like [this](https://github.com/planetarium/lib9c/pull/509/files#diff-466f48999a3b02d0666d42edcec40b3f2712742275766d488c60875746134d6bR131-R144)) instead of global activate states. cc @ipdae

**Review by kfangw — APPROVED** [review]
LGTM.
But, I strongly recommend you to get another approvals by others too before merge it.

File: Lib9c/Action/TransferAsset.cs (hunk 1 above)
Comment (ipdae) [reply Lib9c/Action/TransferAsset.cs:87]: from `ActivateAccount` https://github.com/planetarium/lib9c/blob/rc-v100077/Lib9c/Action/ActivateAccount.cs#L42

**Comment by riemannulus** [comment]
PTAL @ipdae @longfin

**Review by ipdae — APPROVED** [review]
