### PR TITLE
Version up `CombinationEquipment`

### LINKED ISSUE #1814: Broken `CombinationEquipment`'s backward-compatibility
In v100372, there was no `PetIdKey` but it appeared without any action's version bump or optional checking. So it breaks the action's serialization backward-compatibility.

### PR DESCRIPTION
**Pull request by Unengine**
Resolves #1814 .

### CODE REVIEW

File: Lib9c/Action/CombinationEquipment15.cs [hunk 1]
```diff
@@ -0,0 +1,660 @@
...
+using Nekoyume.Model.State;
+using Nekoyume.TableData;
+using Nekoyume.TableData.Crystal;
+using Serilog;
+using static Lib9c.SerializeKeys;
+
+namespace Nekoyume.Action
+{
+    /// <summary>
+    /// Hard forked at https://github.com/planetarium/lib9c/pull/1334
```
Comment (moreal) [inline Lib9c/Action/CombinationEquipment15.cs:25]: I don't want to discuss on this part but this comment doesn't seem to work.

Because https://github.com/planetarium/lib9c/pull/1334 was closed.

You can ignore this comment now but it will be good to discuss about this if you want. The hard-fork comments are still useful?

**Review by sonohoshi — APPROVED** [review]

**Review by moreal — APPROVED** [review]
